# Generated by Django 5.2.17 on 2026-10-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeccionAprendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_error', models.CharField(choices=[('DATO_FALTANTE', 'Dato faltante'), ('FORMATO', 'Formato'), ('PLAZO', 'Plazo'), ('CONTENIDO', 'Contenido'), ('OTRO', 'Otro')], max_length=20)),
                ('problema', models.TextField()),
                ('solucion', models.TextField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='clientes.cliente')),
            ],
            options={
                'verbose_name_plural': 'lecciones aprendidas',
                'ordering': ['-creada_en'],
            },
        ),
    ]
