# Generated by Django 5.2.17 on 2026-10-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conocimiento', '0001_initial'),
        ('entregables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccionaprendida',
            name='entregable_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecciones', to='entregables.entregable'),
        ),
        migrations.AddField(
            model_name='leccionaprendida',
            name='observacion_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leccion', to='entregables.observacion'),
        ),
    ]
