# Generated by Django 5.2.17 on 2026-10-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conocimiento', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccionaprendida',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leccionaprendida',
            name='embedding_modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
