# Generated by Django 5.2.17 on 2026-10-05 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('plazo', models.DateField()),
                ('estado', models.CharField(choices=[('A_REALIZAR', 'A realizar'), ('EN_PROCESO', 'En proceso'), ('VERIFICACION_SENIOR', 'Verificación senior'), ('LISTO_PARA_ENTREGA', 'Listo para entrega'), ('HECHO', 'Hecho')], default='A_REALIZAR', max_length=25)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregables', to='clientes.contrato')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregables_creados', to=settings.AUTH_USER_MODEL)),
                ('junior_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregables_asignados', to=settings.AUTH_USER_MODEL, verbose_name='junior asignado')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregables', to='clientes.plantillatdr')),
                ('senior_revisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregables_a_revisar', to=settings.AUTH_USER_MODEL, verbose_name='senior revisor')),
            ],
            options={
                'ordering': ['plazo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('A_REALIZAR', 'A realizar'), ('EN_PROCESO', 'En proceso'), ('VERIFICACION_SENIOR', 'Verificación senior'), ('LISTO_PARA_ENTREGA', 'Listo para entrega'), ('HECHO', 'Hecho')], max_length=25)),
                ('estado_nuevo', models.CharField(choices=[('A_REALIZAR', 'A realizar'), ('EN_PROCESO', 'En proceso'), ('VERIFICACION_SENIOR', 'Verificación senior'), ('LISTO_PARA_ENTREGA', 'Listo para entrega'), ('HECHO', 'Hecho')], max_length=25)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='entregables.entregable')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_error', models.CharField(choices=[('DATO_FALTANTE', 'Dato faltante'), ('FORMATO', 'Formato'), ('PLAZO', 'Plazo'), ('CONTENIDO', 'Contenido'), ('OTRO', 'Otro')], max_length=20, verbose_name='tipo de error')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('solucion', models.TextField(blank=True, verbose_name='solución')),
                ('resuelta', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='entregables.entregable')),
            ],
            options={
                'verbose_name_plural': 'observaciones',
                'ordering': ['-creada_en'],
            },
        ),
    ]
