# Generated by Django 5.2.17 on 2026-10-05 05:19

import apps.entregables.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestado',
            name='detalle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, upload_to=apps.entregables.models.ruta_adjunto)),
                ('nombre_original', models.CharField(max_length=255, verbose_name='nombre del archivo')),
                ('tipo', models.CharField(choices=[('TDR', 'TDR'), ('BORRADOR', 'Borrador'), ('VERSION_FINAL', 'Versión final'), ('EVIDENCIA', 'Evidencia'), ('OTRO', 'Otro')], max_length=15)),
                ('version', models.PositiveIntegerField(default=1)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='entregables.entregable')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo', '-version'],
                'constraints': [models.UniqueConstraint(fields=('entregable', 'tipo', 'version'), name='adjunto_version_unica')],
            },
        ),
    ]
