# Generated by Django 5.2.17 on 2026-10-05 05:34

import apps.cuentas.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.cuentas.models.UsuarioManager()),
            ],
        ),
    ]
