# Generated by Django 5.2.17 on 2026-10-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('sector', models.CharField(choices=[('BANCA', 'Banca'), ('TELECOM', 'Telecomunicaciones'), ('PUBLICO', 'Sector público')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaTDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('formato', models.CharField(blank=True, help_text='Ej.: Informe en PDF', max_length=100, verbose_name='formato del entregable')),
                ('campos_requeridos', models.JSONField(blank=True, default=list)),
                ('plazo_dias_por_defecto', models.PositiveIntegerField(default=10, verbose_name='plazo por defecto (días)')),
            ],
            options={
                'verbose_name': 'plantilla TDR',
                'verbose_name_plural': 'plantillas TDR',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='número de contrato')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.cliente')),
            ],
            options={
                'ordering': ['numero_contrato'],
            },
        ),
    ]
