# Generated by Django 5.2.17 on 2026-10-05 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='juniors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'JUNIOR'}, related_name='contratos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='senior_responsable',
            field=models.ForeignKey(limit_choices_to={'rol': 'SENIOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='senior responsable'),
        ),
        migrations.AddField(
            model_name='plantillatdr',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Déjelo vacío para una plantilla genérica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='clientes.cliente'),
        ),
    ]
