# Generated by Django 5.2.17 on 2026-10-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillatdr',
            name='adjuntos_requeridos',
            field=models.JSONField(blank=True, default=list, help_text='Tipos de adjunto que el entregable debe tener antes de pasar a Verificación senior.', verbose_name='adjuntos obligatorios'),
        ),
    ]
