# Generated by Django 5.2.17 on 2026-10-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_plantillatdr_adjuntos_requeridos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='activo',
            field=models.BooleanField(default=True, help_text='La baja es lógica: el contrato conserva su historial pero no admite entregables nuevos.'),
        ),
    ]
