# Generated by Django 5.2.17 on 2026-10-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('VENCIMIENTO', 'Vencimiento'), ('OBSERVACION', 'Observación'), ('ASIGNACION', 'Asignación')], max_length=12)),
                ('umbral', models.IntegerField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creada_en', '-id'],
            },
        ),
    ]
