# Generated by Django 5.2.17 on 2026-10-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('VENCIMIENTO', 'Vencimiento'), ('OBSERVACION', 'Observación'), ('ASIGNACION', 'Asignación'), ('VERIFICACION', 'Verificación')], max_length=12),
        ),
    ]
